<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'آیا مطمين هستید که می‌خواهید این آیتم را حذف کنید؟',
    'Color' => 'رنگ ',
    'Create' => 'ایجاد کردن',
    'Create At' => 'تاریخ ساختن',
    'Create Todo' => 'ایجاد todo',
    'Delete' => 'حذف',
    'Detail' => 'جزئیات',
    'Done At' => 'تاریخ انجام',
    'Expired At' => 'تاریخ انقضا',
    'ID' => 'شناسه',
    'Place' => 'مکان',
    'Priority' => 'اولویت',
    'Rank' => 'رتبه',
    'Remind At' => 'تاریخ بیادآوردن',
    'Reset' => 'ریست',
    'Search' => 'جستجو',
    'Status' => 'وضعیت',
    'Title' => 'عنوان',
    'Todos' => 'وضایف',
    'Update' => 'آپدیت',
    'Update {modelClass}: ' => 'آپدیت {modelClass} : ',
];
